name: fitron_app
description: FITRON AI Fitness OS - Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  
  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Camera & Media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  video_player: ^2.8.1
  path_provider: ^2.1.1
  
  # AR & Computer Vision
  ar_flutter_plugin: ^0.7.3
  google_ml_kit: ^0.16.3
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  
  # Real-time Features
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.0
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  
  # Storage & Database
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Forms & Validation
  form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Animations
  flutter_animate: ^4.2.0+1
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Biometrics
  local_auth_android: ^1.0.35
  local_auth_ios: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1
  
  # Linting & Formatting
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  custom_lint_rules: ^0.5.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/models/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 